### ISSUE TITLE
Attribute images not displayed

### ISSUE THREAD

**Issue by scottcwilson** [mc12345678/Stock_By_Attributes_Combined#15]
It seems like based on the check in includes/templates/YOUR_TEMPLATE/templates/tpl_modules_attributes.php
you only display images for non-sba products.

**Comment by mc12345678** [comment]
Images is an aspect covered/addressed by a logged issue in the potteryhouse thread: https://github.com/potteryhouse/stock_by_attribute_1.5.4/issues/29

And comment on line 136 of includes/classes/pad_sba_sequenced_dropdowns.php

It has been possible to apply a plugin against SBA to handle such image attributes; however, improvement upon that is needed and to address more than just a single image for a single option name product. 

If Dynamic Dropdowns are not applied, then the normal image processing is provided regardless of the product being tracked by SBA or not. It is use of DD that does not currently have direct support of images. SBA functions with DD activated or not, the difference is that display and control on the product_info page is limited to standard ZC operation. Attempt to add an invalid SBA tracked product or one that is out-of-stock and not allowed to purchase "out-of-stock" items, then the product is not added to the cart with whatever warnings/notices are normally expected.

So sum in total, images are not addressed when Dynamic Dropdowns are presented to the customer. At the moment the thought is that this is to be deferred until Dynamic Dropdowns at least provides the correct html tags with respect to standard ZC attributes.

**Comment by scottcwilson** [comment]
If anyone is reading this thread and wants to use attribute images with SBA, here's what you do: 

a) In includes/modules/YOUR_TEMPLATE/attributes.php, before the NOTIFY_ATTRIBUTES_MODULE_OPTIONS_SQL notifier fires, back up $options_attributes_image (which is clobbered by that notifier).  Then restore it afterwards.

b) In includes/templates/responsive_sheffield_blue/templates/tpl_modules_attributes.php, at the bottom of the file, if images have not been displayed but $options_attributes_image is not empty, display it. 

c) Set Admin->Configuration->Stock->SBA Display Attributes Images to true.

**Comment by scottcwilson** [comment]
Should not have closed this since people will still have this issue if they want attribute images.

**Comment by mc12345678** [comment]
Better yet, use the latest version of this software (which currently does not include the referenced notifier NOTIFY_ATTRIBUTES_MODULE_OPTIONS_SQL ) and install the software as provided. Therefore such code hacking wouldn't be necessary as suggested/claimed.
