### ISSUE TITLE
Out of stock products still selectable on product page

### ISSUE THREAD

**Issue by jeking928** [mc12345678/Stock_By_Attributes_Combined#8]
With an attribute set at zero quantity, it is still available on the product page. This is true whether Admin>Configure>Dynamic Drop Downs>Show Out of Stock Attributes is set to True or False.

When set to False, there is no indication the attribute is out of stock. However, it cannot be added to the shopping cart. Doing so results in an empty cart.

**Comment by mc12345678** [comment]
There are more settings to restrict selecting than just show out of stock attributes. That particular option/selection allows the display/listing of product that may be out-of-stock. Then there are the settings of marking a product as out-of-stock,  preventing selection of out-of-stock products, etc...

Additionally,  there are those that would still like to be able to select out-of-stock items because that way. They can be back-ordered...

I do not see the problem as simply changing the setting of display out-of-stock product will allow seeing the item on the list, or hide the item from the list. And the list we are talking about here is one controlled by Dynamic Dropdowns. 

As stated elsewhere regarding addressing a single "issue", the complete setup must be provided for the Dynamic Dropdowns configuration,  the stock configuration, whether going to the cart after adding a product or not, etc.... There is no 1 preset switch to do it all,   and various conditions affect (prevent?) others...

**Comment by jeking928** [comment]
Here are the Dynamic Drop Down settings.
![image](https://cloud.githubusercontent.com/assets/8162029/14082652/dd806ab6-f4d6-11e5-920d-0ba4cdacc4ce.png)
If my goal is to have the out of stock attributes display but be marked are out of stock, what do I have wrong?

I'm unable to get the attributes to indicate they are out of stock. I've tried various settings. If I'm just not understanding the function of the settings, then maybe it's user error and not a functional problem.

**Comment by mc12345678** [comment]
How many option names (attributes) are involved?

**Comment by mc12345678** [comment]
Those settings work for me on a clean install to ZC 1.5.3 through 1.5.5 with product having 2 or more options names.

Are you sure you don't also have javascript or html validation issues?

**Comment by jeking928** [comment]
I'm using a clean install of 1.5.5 but only a single attribute.

**Comment by jeking928** [comment]
Just one.

The USB model has zero qty.

http://wheatonwebsiteservices dot 
net/zen155/index.php?main_page=product_info&cPath=1_9&products_id=26

The brown has zero qty.

http://wheatonwebsiteservices dot 
net/zen155/index.php?main_page=product_info&cPath=1_8&products_id=25

**Comment by mc12345678** [comment]
Issue has to do with how controls have been created to treat the SBA Dropdown differently from the standard dropdown and an additional option type has been added along with the way that the attributes.php file has been modified. Anyways, working on a solution which will affect the classes/overrides file.

Anyways, for such "marking" to occur, the option name type needs to be the newly added SBA select list (dropdown) or however it was named. Otherwise the list is unaltered.

**Comment by jeking928** [comment]
I'm not sure what you mean by 'newly added SBA select list'. Can you explain?

**Comment by mc12345678** [comment]
Was trying to type quickly,  which became not specific. 

As part of SBA install, a new option type is added to the default list. So instead of just dropdown, radio, checkbox etc... There is an option of an SBA single attribute dropdown that offers disablement of an attribute selection and a. Little other html related control. Under the revised method of the attributes.php file, that optionhasnt yet been fully factored in. I forgot about it because the defaul: section in the attributes file took care of things.  Also because I hadn't written it, it wasn't a central part of my routine process... It was something that worked and I expected it to continue working.

Anyways, I'll be posting here a quick fix, though it will be a while (hopefully within a day) before I can push the necessary change(s) to github. If at the end of your attributes.php has something other than a notifier below default: then need to just change the option name type to the above attribute type.  If it only has a notifier (and break;) then I'll provide the alternate temporary solution until I get the more correct solution posted to the code.

**Comment by jeking928** [comment]
Very helpful. I did not realize another option type was added. That explains why nothing was being indicated on the product page.

My attributes.php does have something below the notifier. This:

```
    // attributes images table
                // START "Stock by Attributes" SBA
                if (!defined('SBA_SHOW_IMAGE_ON_PRODUCT_INFO') || SBA_SHOW_IMAGE_ON_PRODUCT_INFO != 'false') {
                  $options_attributes_image[] = trim($tmp_attributes_image) . "\n";
                }
                // END "Stock by Attributes" SBA
                $zco_notifier->notify('NOTIFY_ATTRIBUTES_MODULE_OPTION_BUILT', $products_options_names->fields, $options_name, $options_menu, $options_comment, $options_comment_position, $options_html_id, $options_attributes_image);
                //Next Item
                $products_options_names->MoveNext();
              }
              // manage filename uploads
              $_GET['number_of_uploads'] = $number_of_uploads;
              //      zen_draw_hidden_field('number_of_uploads', $_GET['number_of_uploads']);
              zen_draw_hidden_field('number_of_uploads', $number_of_uploads);
            }
```

I don't see any reference to option name type to change.  I can wait until you have time to post the solution so don't feel rushed to explain.

**Comment by mc12345678** [comment]
So, in my previous rereads of this, it seemed like the issue was resolved by changing the option name type to 'SBA Select List (Dropdown) Basic' away from dropdown... But what I believe I understand from the above is that that option does not exist in your list of option name types when accessing the admin option names manager?

Regarding the code and the "notifier" in question, having this code:

```
 // previously this was default: 
                   case ($products_options_names->fields['products_options_type'] == PRODUCTS_OPTIONS_TYPE_SELECT): 
```

was the issue that I was describing, because everything leading up to and including the current code in this section is expecting that $products_options_names->fields['products_options_type'] would be that associated with PRODUCTS_OPTIONS_TYPE_SELECT_SBA which should be assigned an integer value is expected to be locatable in admin/configuration.php?gID=6 (or similar. Easiest to go to one of the configuration items then in the uri change that number to 6)... You would be looking for a statement such as: 'Selection list product option type (SBA)' and the numeric value next to it in the center column.  If that is not the case/not present, then need to re-review the install script to validate that such an upgrade and initial installation happens properly... I had problems with the version I was working with because I was using a database that had some version of SBA previously installed. I hadn't tried to uninstall because I didn't want to have to restore the SBA table, so I did find a few things that could be done to improve the process a little.  Anyways, wanted to verify the current condition before going through too much that may seem unnecessary.

The two conditions of the code I to which I was referring was if the 'default:' section was like this (shortened for clarity) then set the option name as described above in this post:

```
                  default: 
                   // normal dropdown "SELECT LIST" menu display 
                   if (isset($_SESSION['cart']->contents[$prod_id]['attributes'][$products_options_names->fields['products_options_id']])) { 
                     $selected_attribute = $_SESSION['cart']->contents[$prod_id]['attributes'][$products_options_names->fields['products_options_id']]; 
                   } else { 
```

But if it is/was like this, then there are/were additional things to be done which I have manually entered into the observer the information that should be necessary to display attributes that have that option type.

```
                default: 
                   $zco_notifier->notify('NOTIFY_ATTRIBUTES_MODULE_DEFAULT_SWITCH', $products_options_names->fields, $options_name, $options_menu, $options_comment, $options_comment_position, $options_html_id); 
                   break; 
```

**Comment by jeking928** [comment]
The option name type 'SBA Select List (Dropdown) Basic' does exist. Initially, I didn't know SBA added this so never looked for it.

I've set-up a product to use this option name and I think at this point my problem is understanding the appropriate settings in Dynamic Drop Downs. I don't have any multiple attributes to worry about. The problem is with the single attribute. When setting 'Product Info Single Attribute Display Plugin' as a ' single_radioset', the attributes display correctly and the out of stock attribute is marked as such. However....never mind. Further testing and I now see setting 'single_dropdown' does the same thing but as a dropdown.  I had thought I tried all options previously.

So, I think we might be good. I'll keep testing and post back if I discover any issues. Thanks for your persistence and sorry of the root cause all along was my choice of settings.

**Comment by mc12345678** [comment]
So, when the SBA option name is set for an option, dynamic dropdowns are not necessary, because much of the action is already addressed through the SBA settings in the stock configuration menu. This is why Dynamic Dropdowns are setup by default to work only with multiple attributes. Basically, out-of-the-box, SBA offers selection control for single attributes set as SBA dropdowns, and then for multiple attributes, basically if the page is html validated.  :P single attributes using DD have not been so refined because there has not been a need... Already covered as stated above...

So I advise to return to looking at the stock configuration section and disabling single DD control. (Setting. The value back to 2 in DD configuration.)

**Comment by jeking928** [comment]
When I set DD Config to 2, the drop-down list on the product page does not display. This is my stock config settings.

![image](https://cloud.githubusercontent.com/assets/8162029/14140687/2a8e7888-f640-11e5-993e-2794bc0b105a.png)

**Comment by mc12345678** [comment]
Okay, I had like 20 mins to review, try, and commit, but there are some changes posted that showed success with my one sample but. That sample was the last option value, so I don't know yet what happens if like the first or "middle" option value goes out-of-stock...  But at least I could get the result(s) desired/expected (again).

**Comment by mc12345678** [comment]
Fyi, just tested the code with the first attribute in the list being out-of-stock and it only placed the applicable out-of-stock option values as out-of-stock. Wish I knew why I commented out the code that I did. I thought that I remembered something else being negatively affected, but it looks like it is working properly for SBA. Controlled items when usng the SBA option name for single attributes. Still have several other tests to try/verify including the effect with multiple attributes using the SBA option name, just to be sure that there is no conflict in provided information.

**Comment by jeking928** [comment]
I'm got some time tomorrow, I'll do a fresh install and some more 
testing too.

**Comment by jeking928** [comment]
To avoid my mistake, is the master branch correct one to test?

**Comment by mc12345678** [comment]
Yes.  Master branch for basic operation.

**Comment by jeking928** [comment]
Finally got the time to install and test. Functionality looks good, no issues. In the file structure, there were two issues:
1. tpl_checkout_confirmation_default.php and tpl_shopping_cart_default.php exist in  \includes\templates\YOUR_TEMPLATE\templates and \1_5_5\includes\templates\YOUR_TEMPLATE\templates
   I think we discussed removing them from \includes\templates\YOUR_TEMPLATE\templates and putting them into the version specific folders
2. checkout_success\header_php_sba.php is missing in \1_5_5\includes\modules\pages

**Comment by mc12345678** [comment]
1. Yeah, stll hadn't gotten around to that shift of files.
2. Unnecessary, because of a post and discussion on the code at that area, the problem being fixed with that extra file has been fixed in the base code. So, no need to add that extra file in ZC 1.5.5.

Basically, without trimming down the capabilities of SBA, it has become more of a plugin and less of a modification... Still has a ways to go, and unfortunately at the moment the one thing that is holding up removal from editing so many files is the customid display.  Seems like it will be possible to incorporate it "earlier" so that there are less template file edits, etc... But if only that were the one thing that still needed to be addressed.

**Comment by jeking928** [comment]
> checkout_success\header_php_sba.php is missing in \1_5_5\includes\modules\pages
> 
> Unnecessary, because of a post and discussion on the code at that area, the problem being fixed with that extra file has been fixed in the base code. So, no need to add that extra file in ZC 1.5.5.

The installation reported this as an error. That's what caught my attention.

Are you saying it's not needed for ZC 1.5.5? Because this file is included in the 1.5.1/3/4 folders for this install.

**Comment by mc12345678** [comment]
Yeah, that's one of the problems with auto-installers/checkers... They think they're smarter than what the code requires. Correct, ZC 1.5.5 checkout_success now contains by default in the sql for identifying products to be flagged for notification using distinct. The provides the result sought after product purchase that regardless which variants of a product were purchased, notification is regarding the product not it's variants. (Obviously an area that could be expanded later, but still bigger fish). Will revisit the installer. Have an added feature coming that need to address/finish first. Attributes grid..

**Comment by jeking928** [comment]
Ah, I did wonder if that might have been this issue.

mc12345678 wrote:

**Comment by jeking928** [comment]
I've finally got around to installing this on my dog rescue site. The problem is the same, the option name ' SBA Select List (Dropdown) Basic' is not listed. I've re-read but don't see how this was solved.

**Comment by mc12345678** [comment]
Still not sure what is not working. I did find a part of the code wouldn't have worked quite like expected if the SBA basic dropdown option was already installed in a cart, but the "solution" for the last time this issue was identified was provided [here in issue #9](https://github.com/mc12345678/Stock_By_Attributes_Combined/issues/9), but I thought that was where possibly normal dropdowns possibly didn't work.  Before running the patch identified in that issue, was a previous version of SBA installed on that system? 

Said that you installed this onto that system, but the previous issue appears to have been that it was that it was listed but it wouldn't display the modified dropdowns and that the applicable "internal" constant had to be defined.  I'm curious that with the newly installed includes/modules/YOUR_TEMPLATE/attributes.php file, do any dropdowns display? I'm thinking I will need to add a ZC "patch" to make the plugin successful in light of other older plugins that might have removed some necessary data.

I updated the install file last night with two corrections. One was to properly use the function RecordCount() on a database lookup, the other was to add a define upon successful insertion of the applicable information into the database when it was previously identified to not have existed.  This supports the session continuing forward with the define applied and not depend on a database lookup/reload.

Further before applying the patch identified in Issue #9, could you please login again and verify that the option is not presented?

**Comment by jeking928** [comment]
Issue #9, that is the answer I was looking for yesterday. I did log in and confirmed the option was not present. So I ran the sql and now all is good. Ironically, this is the dog rescue site I had mentioned in that issue. Finally getting around to updating it.

**Comment by jeking928** [comment]
I am now getting a 'method error' when on the shopping cart, checkout shipping and checkout payment pages. No error in the logs folder. This is with just one item in the cart that is tracked by SBA. Testing, I get the same 'method error' when only a non-SBA item is in the cart as well.

**Comment by mc12345678** [comment]
This 'method error' is it like a javascript error? Stated not getting any logged error (should always verify that the lack of a logged error is because one wasn't generated rather than one not being written) I do this typically by quickly creating a php file in the admin area that loads the application_top file and has an incorrect SQL statement.  Then once logged into the admin to attempt to access the file, see that an error has been generated on screen then verify that the error is logged into the logs directory.

Curious how to recreate the method error or what to look for.  Could there be a template merge issue?

**Comment by jeking928** [comment]
Error logs are being written, I do a different method but also cause an error to be sure they are being written. It could be a javascript error. I mentioned it here because it did not occur until after I ran the sql statement to resolve the issue with SBA. I'll investigate.

**Comment by mc12345678** [comment]
I've been looking through the install code and I do not see:
1) an "exit" step that would stop execution other than an error (which would be expected to be logged)
2) how on a system that did not have this previously installed that the PRODUCTS_OPTIONS_TYPE_SELECT_SBA constant and associated option type of 'SBA Select List (Dropdown) Basic' wouldn't be generated/created.  Certainly the one liner sql statement will accomplish part of the task, but that comes directly out of the code.  It's obviously happened (twice? or really is it once but on a backup of the system as well as on the live system as well?)
3) how this doesn't work because when I manually removed the database entries added by the section of the code in the function insertSBAproductsOptionsTypes, then ran the full install/upgrade (which doesn't lose the SBA variant table data, that it inserted the values as expected/where expected...  I caution using this approach because if any other product option types have been added after SBA, then the number associated to product that had used the old number will not be associated with any specific option type until the data is manually modified to again associate with existing product type identifiers.

So, really wish this aspect of the installation to not to be an issue for anyone else, but don't appear to have much on which to go with/to. Appreciate any help/information you can find/identify.

**Comment by jeking928** [comment]
At this point, the 'method error' is likely a javascript issue. Still looking into it though.

You know, this is actually the same site as before. It did have SBA installed previously and a few other plugins, but nothing too crazy. Since it has not been reported elsewhere and I've upgraded other sites without seeing this, it could just be something odd going here.  I'd too would like to know why. If I ever find a clue, I'll share it.

**Comment by mc12345678** [comment]
Checking in on this issue thread. Would like to close it if considered acceptable. If option is available for you to do so and it seems "resolved" please close it with any available explanation. 

Thank you also for taking part in this project. User input is the only thing that can make it more universally friendly and capable.

**Comment by jeking928** [comment]
I guess I never follow-up. the problem no longer exists. However, I can say what the fix was. My lost post was 10 months ago. :-) It was the only site I had this issue, so very likely something unique with that scenario.
